name: Build Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    environment: laceworkscanner
    
    steps:
    - shell: bash
    env:
      SUPER_SECRET: ${{ secrets.LW_ACCESS_TOKEN }}
    run: |
      echo "$SUPER_SECRET"
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag whalesong:latest
    - uses: lacework/lw-scanner-action@v1.0.0
      name: Scan container images for vulnerabitilies using Lacework
      with:
        LW_ACCOUNT_NAME: ${{ secrets.LW_ACCOUNT_NAME }} 
        LW_ACCESS_TOKEN: ${{ secrets.LW_ACCESS_TOKEN }}
        IMAGE_NAME: whalesong
        IMAGE_TAG: latest
        SAVE_RESULTS_IN_LACEWORK: true
        SAVE_BUILD_REPORT: true
        BUILD_REPORT_FILE_NAME: scanreport.htm
